# -*- mode: ruby -*-
# vi: set ft=ruby :

SubNet       = "192.168.10"
Domain       = "oloc"
topology     = "%-15s %-10s %s" % ["IP:","Ports:","Host:"]
ansibleHosts = "# Generated by Vagrantfile\n[all]\n"

fileContent = JSON.parse(File.read("./provision.json"), symbolize_names: true)
fileContent.each do |node|
  @hostsList = "#{@hostsList}#{SubNet}.#{node[:iplastdigit]}\t#{node[:name]}.#{Domain} #{node[:name]}\n"
  topology = "#{topology}\n%-15s 22=>22%-4s %s" % \
    ["#{SubNet}.#{node[:iplastdigit]}","#{node[:iplastdigit]}","#{node[:name]}.#{Domain}"]
  ansibleHosts = "#{ansibleHosts}#{node[:name]} ansible_user=vagrant " + \
               "ansible_host=127.0.0.1 ansible_port=22#{node[:iplastdigit]} " + \
               "ansible_ssh_private_key_file=.vagrant/machines/#{node[:name]}/virtualbox/private_key\n"
end
# To update the /etc/hosts with all the nodes
hostsListUpdate="echo -e \"#{@hostsList}\\n\" >> /etc/hosts"
# To Create an ansible Hosts with ansible_ssh_port and so on
File.write('./vagrant_hosts',"#{ansibleHosts}")
# Status displays topology
if ARGV[0] == 'status'
  puts "#{topology}\n\n"
end

# Vagrantfile API/syntax version.
# Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "debian/jessie64"
  # To prevent tty errors
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
  fileContent.each do |node|
    config.vm.define node[:name] do |machine|
      machine.vm.hostname = "#{node[:name]}.#{Domain}"
      machine.vm.network :private_network, ip: "#{SubNet}.#{node[:iplastdigit]}"
      machine.vm.provision :shell, :inline => hostsListUpdate

      machine.vm.provider 'virtualbox' do |vb|
        vb.customize ["modifyvm", :id, "--name", node[:name]]
        vb.customize ["modifyvm", :id, "--natpf1", ",tcp,127.0.0.1,22#{node[:iplastdigit]},,22"]
      end

      if node == fileContent.last
        machine.vm.provision :ansible do |ansible|
          # Disable default limit to connect to all the machines
          ansible.limit          = 'all'
          ansible.playbook       = "playbook.yml"
          ansible.inventory_path = "vagrant_hosts" # Previously generated
          ansible.raw_arguments  = [
            "--verbose"]
        end
      end

    end
  end
end
